config/routes.rb
Auth::Application.routes.draw do

  resources :users, only: [:new, :create]
  resource :session, only: %w(new create destroy)

  get '/dashboard', to: "dashboard#index"
  root "welcome#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def require_user!
    if current_user.nil?
      flash[:notice] = "You are not allowed there."
      redirect_to new_session_url
    end
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :require_user!

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Signed in"
      redirect_to dashboard_url
    else
      flash.now[:notice] = "Email/password did not match."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out!"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      flash[:notice] = "Thanks for creating an account."
      session[:user_id] = @user.id
      redirect_to dashboard_url
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name, :email, :password, :password_confirmation
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p><b>This is PRIVATE stuff only logged in you you should see!</b></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auth</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Dashboard", dashboard_path %></li>
    </ul>
    <ul>
      <% if current_user %>
        <li>Welcome <%= current_user.name %>!</li>
        <li><%= link_to 'Sign Out (destroy session)', session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Register (new user)', new_user_path %></li>
        <li><%= link_to 'Sign In (create session)', new_session_path %></li>
      <% end %>
    </ul>
  </nav>

  <%= notice %>
  <%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<h2>Create your account here!</h2>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit 'Create My Account Already!' %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p><b>This is public stuff everyone can see!</b></p>

<h3>To Do:</h3>
<ol>
  <li>Route to sign in page and the create a user page as sigular routes.</li>
  <li>Create a user, sign them in.</li>
  <li>Show logged in status when signed in.</li>
  <li>Allow them to sign out.</li>
  <li>Allow them to sign back in.</li>
  <li>Only let signed in people view the dashboard.</li>
</ol>

<h4>Notes:</h4>
<ul>
  <li>After signing in, you should be redirected to the dashboard.</li>
  <li>After signing out, you should be redirected to the home page.</li>
</ul>